<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-BTG7UVQ" ignored="0" name="Surefire test" tests="17" failures="3" timestamp="2022-12-13T23:18:08 EET" time="223.597" errors="0">
  <testcase name="runScenario" time="12.835" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="13.27" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="11.535" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="9.426" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="9.631" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="11.781" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="12.719" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="13.203" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="10.305" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="12.565" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at org.example.stepDefs.D06_followUsStepDef.isOpenedInNewTab(D06_followUsStepDef.java:43)
at ✽."https://demo.nopcommerce.com/new-online-store-is-open" is opened in new tab(file:///C:/Users/Al-Hussein/Desktop/Project%20two/MyFirstTestAutomationProject/src/main/resources/features/F06_followUs.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="11.057" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="11.397" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="11.38" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="URL of First Slide expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: URL of First Slide expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.example.stepDefs.D07_homeSliderStepDef.first_slide_displayed(D07_homeSliderStepDef.java:22)
at ✽.relative product for first slider is displayed(file:///C:/Users/Al-Hussein/Desktop/Project%20two/MyFirstTestAutomationProject/src/main/resources/features/F07_homeSlider.feature:7)
... Removed 5 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="11.717" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="URL of Second Slide expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: URL of Second Slide expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]
at org.example.stepDefs.D07_homeSliderStepDef.second_slide_displayed(D07_homeSliderStepDef.java:36)
at ✽.relative product for second slider is displayed(file:///C:/Users/Al-Hussein/Desktop/Project%20two/MyFirstTestAutomationProject/src/main/resources/features/F07_homeSlider.feature:12)
... Removed 5 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="21.037" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="24.394" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="14.738" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Surefire test -->
